freechal_id = ''
freechal_password = ''
freechal_board_url = 'http://bbs.freechal.com/ComService/Activity/ABBS/CsBBSList.asp?GrpId=1630900&ObjSeq=15'
article_filename = 'article'
comment_filename = 'comment'
